version: "3.1"
services:
    dstargateway:
        image: dstargateway
        build:
            context: .
            dockerfile: Docker/Dockerfile
        restart: always
        network_mode: "host"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        volumes:
            - ./docker-data:/usr/local/etc/dstargateway.d/
            - ./docker-logs:/var/log/dstargateway/
        entrypoint: /start-dstargateway.sh

    dstartimeserver:
        image: dstargateway
        restart: always
        network_mode: "host"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        volumes:
            - ./docker-data:/usr/local/etc/dstargateway.d/
            - ./docker-logs:/var/log/dstargateway/
        entrypoint: /start-timeserver.sh
